version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: retail_weather_db
    environment:
      POSTGRES_DB: retail_weather
      POSTGRES_USER: analyst
      POSTGRES_PASSWORD: analyst_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: